apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dejankov@gmail.com
    privateKeySecretRef:
      # name secret where the certificate will be stored
      name: letsencrypt
    # set solver to global nginx-controller
    solvers:
      - http01:
          ingress:
            class:  nginx
