apiVersion: apps/v1
kind: Deployment
metadata:
  name: ediscovery-app
  labels:
    app: ediscovery

spec:
  selector:
    matchLabels:
      app: ediscovery

  replicas: 1

  template:
    metadata:
      labels:
        app: ediscovery

    spec:
      restartPolicy: Always

      containers:
        - name: ediscovery
          image: 536697232357.dkr.ecr.eu-west-3.amazonaws.com/ediscovery:latest
          imagePullPolicy: Always
          env:
            - name: LOG_LEVEL
              value: INFO
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ediscovery
spec:
  selector:
    app: ediscovery
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
