name: Build and Push Docker Image to GCR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to GKE
        uses: google-github-actions/auth@v1
        with:
          project_id: bustling-syntax-439308-h6
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Build, tag, and push Docker image to GCR
        env:
          GCR_REPOSITORY: gcr.io/bustling-syntax-439308-h6/ediscovery
          IMAGE_TAG: latest
        run: |
          docker build -t $GCR_REPOSITORY:$IMAGE_TAG .
          docker push $GCR_REPOSITORY:$IMAGE_TAG
